name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Cache dependencies
        run: deno task cache

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: paquet
          entrypoint: ./src/main.ts
          import-map: ./src/import_map.json
